controller_list:
  - name: fake_tm5_700_arm_controller
    type: $(arg execution_type)
    joints:
      - shoulder_1_joint
      - shoulder_2_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_gripper_controller
    type: $(arg execution_type)
    joints:
      - robotiq_85_left_knuckle_joint
initial:  # Define initial robot poses.
  - group: tm5_700_arm
    pose: All0
  - group: gripper
    pose: Open