# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: tm5_700_arm
  joint_model_group_pose: All0
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - shoulder_1_joint
    - shoulder_2_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
    - robotiq_85_left_knuckle_joint
  sim_control_mode: 1  # 0: position, 1: velocity

# Publish all joint states
# Creates the /joint_states topic necessary in ROS
tm5_700_robotiq:

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  tm5_700_arm_controller:  
    type: position_controllers/JointTrajectoryController
    #action_ns: scaled_pos_traj_controller/follow_joint_trajectory
    joints:
      - shoulder_1_joint
      - shoulder_2_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      shoulder_1_joint: {trajectory: 1, goal: 0.5}
      shoulder_2_joint: {trajectory: 1, goal: 0.5}
      elbow_joint: {trajectory: 1, goal: 0.5}
      wrist_1_joint: {trajectory: 1, goal: 0.5}
      wrist_2_joint: {trajectory: 1, goal: 0.5}
      wrist_3_joint: {trajectory: 1, goal: 0.5}
    gains:
      shoulder_1_joint: {p: 10,  i: 0.0, d: 0.1, i_clamp: 1}
      shoulder_2_joint: {p: 10,  i: 0.1, d: 0.2, i_clamp: 1}
      elbow_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
      wrist_1_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
      wrist_2_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
      wrist_3_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10

  gripper_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - robotiq_85_left_knuckle_joint
    gains:
      robotiq_85_left_knuckle_joint: {p: 40, i: 1, d: 0, i_clamp: 1}

      
controller_list:
  - name: tm5_700_robotiq/tm5_700_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - shoulder_1_joint
      - shoulder_2_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: tm5_700_robotiq/gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
       - robotiq_85_left_knuckle_joint

