tm5_700_robotiq:

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  tm5_700_arm_controller:  
    type: position_controllers/JointTrajectoryController
    joints:
      - shoulder_1_joint
      - shoulder_2_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    gains:
      shoulder_1_joint: {p: 10,  i: 0.0, d: 0.1, i_clamp: 1}
      shoulder_2_joint: {p: 10,  i: 0.0, d: 0.1, i_clamp: 1}
      elbow_joint: {p: 10,  i: 0.0, d: 0.1, i_clamp: 1}
      wrist_1_joint: {p: 10,  i: 0.0, d: 0.1, i_clamp: 1}
      wrist_2_joint: {p: 10,  i: 0.0, d: 0.1, i_clamp: 1}
      wrist_3_joint: {p: 10,  i: 0.0, d: 0.1, i_clamp: 1}
  
  gripper_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - robotiq_85_left_knuckle_joint
    gains:
      robotiq_85_left_knuckle_joint: {p: 40,  i: 1, d: 0.0, i_clamp: 1}


controller_list:
  - name: tm5_700_robotiq/tm5_700_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - shoulder_1_joint
      - shoulder_2_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
      
  - name: tm5_700_robotiq/gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - robotiq_85_left_knuckle_joint